<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 ./src/lib/3d-models/art.glb --transform
-->

<script>
  import { Group } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf } from "@threlte/extras";
  import { afterUpdate } from "svelte";
  import { AutoColliders, RigidBody } from "@threlte/rapier";

  export const ref = new Group();
  export let loaded = false;

  const gltf = useGltf("/src/lib/3d-models/art-transformed.glb", {
    useDraco: true,
  });

  afterUpdate(() => {
    gltf.then(() => {
      loaded = true;
    });
  });

  const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={[50.75, 0.9, 50.75]}>
      <RigidBody type={"fixed"} dominance={0}>
        <AutoColliders shape={"trimesh"}>
          <T.Mesh
            geometry={gltf.nodes.Cube001.geometry}
            material={gltf.materials["Material.001"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Cube001_1.geometry}
            material={gltf.materials.floor}
          />
          <T.Mesh
            geometry={gltf.nodes.Cube001_2.geometry}
            material={gltf.materials.frame}
          />
          <T.Mesh
            geometry={gltf.nodes.Cube001_3.geometry}
            material={gltf.materials["painting.001"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Cube001_4.geometry}
            material={gltf.materials["painting 2"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Cube001_5.geometry}
            material={gltf.materials["painting 3"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Cube001_6.geometry}
            material={gltf.materials["painting 4"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Cube001_7.geometry}
            material={gltf.materials["painting 6"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Cube001_8.geometry}
            material={gltf.materials["painting 7"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Cube001_9.geometry}
            material={gltf.materials["Material.002"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Cube001_10.geometry}
            material={gltf.materials.celling}
          />
        </AutoColliders>
      </RigidBody>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
