<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 ./public/model.glb --transform
-->

<script>
  import { Group } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf } from "@threlte/extras";

  export const ref = new Group();

  const gltf = useGltf("./src/lib/3d-models/model-transformed.glb", {
    useDraco: true,
  });

  const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={[10.38, 0.1, 10.38]}>
      <T.Mesh
        geometry={gltf.nodes.Cube001_1.geometry}
        material={gltf.materials["Material.001"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube001_2.geometry}
        material={gltf.materials["Material.002"]}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Cube001.geometry}
      material={gltf.nodes.Cube001.material}
      position={[-6.37, 1.34, 5.48]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube002.geometry}
      material={gltf.nodes.Cube002.material}
      position={[7.94, 1.34, -0.95]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
